local addonName, EL = ...

-- EmberLedger localization framework.
--
-- The addon uses English strings as localization keys. This keeps call sites
-- readable while allowing future locale tables to override only the strings
-- that need translation. Strings not present in the active locale table fall
-- back to English automatically.

EL.locale = (GetLocale and GetLocale()) or "enUS"
EL.L = EL.L or {}

local L = EL.L

local enUS = {
    ["EmberLedger"] = "EmberLedger",
    ["EmberLedger Options"] = "EmberLedger Options",
    ["Profession Tracking"] = "Profession Tracking",
    ["Options"] = "Options",
    ["Restore"] = "Restore",
    ["Character"] = "Character",
    ["P1"] = "P1",
    ["Conc 1"] = "Conc 1",
    ["P2"] = "P2",
    ["Conc 2"] = "Conc 2",
    ["Moxie"] = "Moxie",
    ["Next"] = "Next",
    ["CD"] = "CD",
    ["Mulch"] = "Mulch",
    ["Unknown"] = "Unknown",
    ["Unlearned"] = "Unlearned",
    ["READY"] = "READY",
    ["charges"] = "charges",
    ["Shared pool"] = "Shared pool",
    ["Shared cooldown"] = "Shared cooldown",
    ["ready"] = "ready",
    ["next"] = "next",
    ["full"] = "full",
    ["Open profession to refresh."] = "Open profession to refresh.",
    ["Profession Cooldowns"] = "Profession Cooldowns",
    ["No supported profession cooldowns tracked."] = "No supported profession cooldowns tracked.",
    ["Profession"] = "Profession",
    ["Cooldown"] = "Cooldown",
    ["Realm"] = "Realm",
    ["Last seen"] = "Last seen",
    ["Professions"] = "Professions",
    ["Concentration"] = "Concentration",
    ["Alert threshold"] = "Alert threshold",
    ["Full"] = "Full",
    ["Ready"] = "Ready",
    ["Full in"] = "Full in",
    ["Now"] = "Now",
    ["global"] = "global",
    ["override"] = "override",
    ["Concentration: not tracked"] = "Concentration: not tracked",
    ["No professions tracked yet."] = "No professions tracked yet.",
    ["Imbued Mulch"] = "Imbued Mulch",
    ["Ready at"] = "Ready at",
    ["In bags"] = "In bags",
    ["No Imbued Mulch data tracked."] = "No Imbued Mulch data tracked.",
    ["Current character"] = "Current character",
    ["Pinned"] = "Pinned",
    ["Row interactions"] = "Row interactions",
    ["Alt-click: unpin character"] = "Alt-click: unpin character",
    ["Alt-click: pin character"] = "Alt-click: pin character",
    ["Right-click: hide character"] = "Right-click: hide character",
    ["Shift-right-click: remove EmberLedger data"] = "Shift-right-click: remove EmberLedger data",
    ["just now"] = "just now",
    ["%dm ago"] = "%dm ago",
    ["%dh %02dm ago"] = "%dh %02dm ago",
    ["%dd ago"] = "%dd ago",
    ["Cooldown tooltip unavailable: %s"] = "Cooldown tooltip unavailable: %s",

    ["Currently tracking: %s"] = "Currently tracking: %s",
    ["All supported cooldown crafts are now shown."] = "All supported cooldown crafts are now shown.",
    ["Quick launcher and window toggle."] = "Quick launcher and window toggle.",
    ["Next CD: Ready on %s"] = "Next CD: Ready on %s",
    ["Next CD: %s in %s"] = "Next CD: %s in %s",

    ["Item"] = "Item",
    ["Qty"] = "Qty",
    ["Value"] = "Value",
    ["Total"] = "Total",
    ["Ready: %d | Soon: %d | Mulch: %d"] = "Ready: %d | Soon: %d | Mulch: %d",

    ["No tracked characters yet. Open professions to scan characters."] = "No tracked characters yet. Open professions to scan characters.",
    ["All tracked characters are hidden. Use Restore to show them."] = "All tracked characters are hidden. Use Restore to show them.",
    ["No attention rows. Restore hidden or turn off Attention Only."] = "No attention rows. Restore hidden or turn off Attention Only.",
    ["No characters need attention."] = "No characters need attention.",
    ["No visible character data. Open a profession window to refresh."] = "No visible character data. Open a profession window to refresh.",

    ["Sort by %s"] = "Sort by %s",
    ["Click again to reverse the order."] = "Click again to reverse the order.",
    ["EmberLedger options"] = "EmberLedger options",
    ["Restore hidden characters"] = "Restore hidden characters",
    ["Right-click a row to hide a character."] = "Right-click a row to hide a character.",
    ["Collapse or expand character cooldowns"] = "Collapse or expand character cooldowns",
    ["Resize tracker height"] = "Resize tracker height",
    ["Drag to change how many character rows are visible."] = "Drag to change how many character rows are visible.",
    ["Width remains automatic based on visible columns."] = "Width remains automatic based on visible columns.",
    ["Double-click to reset automatic height."] = "Double-click to reset automatic height.",

    ["General"] = "General",
    ["Launcher"] = "Launcher",
    ["Session"] = "Session",
    ["Main Window"] = "Main Window",
    ["Action Bar"] = "Action Bar",
    ["Performance"] = "Performance",
    ["Maintenance"] = "Maintenance",
    ["Maintenance / Resets"] = "Maintenance / Resets",
    ["Information"] = "Information",
    ["Version: %s"] = "Version: %s",
    ["Version %s"] = "Version %s",
    ["Profession tracking, Imbued Mulch cooldowns, and session analytics for your alt army."] = "Profession tracking, Imbued Mulch cooldowns, and session analytics for your alt army.",
    ["Open EmberLedger Settings"] = "Open EmberLedger Settings",

    ["Reset"] = "Reset",
    ["Clear History"] = "Clear History",
    ["Reset Lifetime"] = "Reset Lifetime",
    ["Unhide All"] = "Unhide All",
    ["Remove Data"] = "Remove Data",
    ["Reset all EmberLedger window positions? Scale and visibility settings will be kept."] = "Reset all EmberLedger window positions? Scale and visibility settings will be kept.",
    ["Reset the current session totals and tracked item list?"] = "Reset the current session totals and tracked item list?",
    ["Clear all saved account-wide session history? This cannot be undone."] = "Clear all saved account-wide session history? This cannot be undone.",
    ["Reset EmberLedger lifetime session stats? This cannot be undone. Session history will not be deleted."] = "Reset EmberLedger lifetime session stats? This cannot be undone. Session history will not be deleted.",
    ["Unhide all hidden characters and return them to the main window table?"] = "Unhide all hidden characters and return them to the main window table?",
    ["Remove all EmberLedger data for currently hidden characters? This only affects EmberLedger saved data and cannot be undone."] = "Remove all EmberLedger data for currently hidden characters? This only affects EmberLedger saved data and cannot be undone.",
    ["Remove EmberLedger data for %s? This only affects EmberLedger saved data and cannot be undone."] = "Remove EmberLedger data for %s? This only affects EmberLedger saved data and cannot be undone.",
    ["Remove all pinned character markers? Character data will not be deleted."] = "Remove all pinned character markers? Character data will not be deleted.",
    ["Confirmation dialog unavailable. No data was removed."] = "Confirmation dialog unavailable. No data was removed.",

    ["Commands:"] = "Commands:",
    ["/el or /ember - Toggle EmberLedger launcher/main view."] = "/el or /ember - Toggle EmberLedger launcher/main view.",
    ["/el main - Toggle the main tracking window."] = "/el main - Toggle the main tracking window.",
    ["/el settings - Open Options."] = "/el settings - Open Options.",
    ["/el session - Toggle the standalone Session window."] = "/el session - Toggle the standalone Session window.",
    ["/el history - Toggle Session History / Stats."] = "/el history - Toggle Session History / Stats.",
    ["/el session start or /el session resume - Resume session tracking."] = "/el session start or /el session resume - Resume session tracking.",
    ["/el session pause - Pause session tracking."] = "/el session pause - Pause session tracking.",
    ["/el refresh - Refresh tracked profession data."] = "/el refresh - Refresh tracked profession data.",
    ["/el scale - Show the current main window scale."] = "/el scale - Show the current main window scale.",
    ["/el scale 0.85 - Set main window scale from 0.60 to 1.40."] = "/el scale 0.85 - Set main window scale from 0.60 to 1.40.",
    ["/el threshold 900 - Set concentration alert threshold."] = "/el threshold 900 - Set concentration alert threshold.",
    ["/el lock or /el unlock - Lock or unlock EmberLedger windows."] = "/el lock or /el unlock - Lock or unlock EmberLedger windows.",
    ["/el reset layout - Reset window positions."] = "/el reset layout - Reset window positions.",
    ["/el reset session - Reset current session totals."] = "/el reset session - Reset current session totals.",
    ["/el restore or /el restore hidden - Restore hidden characters."] = "/el restore or /el restore hidden - Restore hidden characters.",
    ["/el reset pinned - Remove all pinned markers."] = "/el reset pinned - Remove all pinned markers.",
    ["Window scale set to %.2f."] = "Window scale set to %.2f.",
    ["Use /el scale 0.6 through /el scale 1.4"] = "Use /el scale 0.6 through /el scale 1.4",
    ["Current window scale: %.2f. Use /el scale 0.85, /el scale 1, etc."] = "Current window scale: %.2f. Use /el scale 0.85, /el scale 1, etc.",
    ["Windows locked. Hold Shift and drag to move them."] = "Windows locked. Hold Shift and drag to move them.",
    ["Windows unlocked."] = "Windows unlocked.",
    ["Refreshed."] = "Refreshed.",
    ["Profession identity refreshed."] = "Profession identity refreshed.",
    ["Profession identity could not be refreshed yet."] = "Profession identity could not be refreshed yet.",
    ["Session tracking resumed."] = "Session tracking resumed.",
    ["Session tracking paused."] = "Session tracking paused.",
    ["Concentration alert threshold set to %d."] = "Concentration alert threshold set to %d.",
    ["Welcome to EmberLedger"] = "Welcome to EmberLedger",
    ["EmberLedger learns your profession characters as you visit them.\n\nGetting Started:\n1. Log into each profession character you want to track.\n2. Open the Trade Skill window (press K, then choose a profession) once.\n3. Repeat this for each profession alt.\n\nConcentration, Artisan Moxie, and profession cooldowns are only available after opening the profession window. Your dashboard updates automatically as more characters are scanned.\n\nTip: /el help lists all commands and row interactions."] = "EmberLedger learns your profession characters as you visit them.\n\nGetting Started:\n1. Log into each profession character you want to track.\n2. Open the Trade Skill window (press K, then choose a profession) once.\n3. Repeat this for each profession alt.\n\nConcentration, Artisan Moxie, and profession cooldowns are only available after opening the profession window. Your dashboard updates automatically as more characters are scanned.\n\nTip: /el help lists all commands and row interactions.",
    ["Open Options"] = "Open Options",
    ["Got It"] = "Got It",
}

for key, value in pairs(enUS) do
    if L[key] == nil then
        L[key] = value
    end
end

-- Translator ZamestoTV
local localeOverrides = {
    ["ruRU"] = {
    ["EmberLedger Options"] = "Настройки EmberLedger",
    ["Profession Tracking"] = "Отслеживание профессий",
    ["Options"] = "Настройки",
    ["Restore"] = "Восстановить",
    ["Character"] = "Персонаж",
    ["P1"] = "П1",
    ["Conc 1"] = "Конц 1",
    ["P2"] = "П2",
    ["Conc 2"] = "Конц 2",
    ["Moxie"] = "Сноровка",
    ["Next"] = "След.",
    ["CD"] = "КД",
    ["Mulch"] = "Мульча",
    ["Unknown"] = "Неизвестно",
    ["Unlearned"] = "Не изучено",
    ["READY"] = "ГОТОВО",
    ["charges"] = "заряды",
    ["Shared pool"] = "Общий запас",
    ["Shared cooldown"] = "Общее время восстановления",
    ["ready"] = "готово",
    ["next"] = "след.",
    ["full"] = "полн.",
    ["Open profession to refresh."] = "Откройте профессию для обновления данных.",
    ["Profession Cooldowns"] = "Время восстановления профессий",
    ["No supported profession cooldowns tracked."] = "Нет отслеживаемых кулдаунов для поддерживаемых профессий.",
    ["Profession"] = "Профессия",
    ["Cooldown"] = "Восстановление",
    ["Realm"] = "Игровой мир",
    ["Last seen"] = "Последний вход",
    ["Professions"] = "Профессии",
    ["Concentration"] = "Концентрация",
    ["Alert threshold"] = "Порог оповещения",
    ["Full"] = "Заполнено",
    ["Ready"] = "Готово",
    ["Full in"] = "Заполнится через",
    ["Now"] = "Сейчас",
    ["global"] = "общее",
    ["override"] = "переопределение",
    ["Concentration: not tracked"] = "Концентрация: не отслеживается",
    ["No professions tracked yet."] = "Профессии еще не отслеживаются.",
    ["Imbued Mulch"] = "Насыщенная мульча",
    ["Ready at"] = "Будет готово в",
    ["In bags"] = "В сумках",
    ["No Imbued Mulch data tracked."] = "Нет данных об отслеживании Насыщенной мульчи.",
    ["Current character"] = "Текущий персонаж",
    ["Pinned"] = "Закреплено",
    ["Row interactions"] = "Взаимодействие со строками",
    ["Alt-click: unpin character"] = "Alt + клик: открепить персонажа",
    ["Alt-click: pin character"] = "Alt + клик: закрепить персонажа",
    ["Right-click: hide character"] = "ПКМ: скрыть персонажа",
    ["Shift-right-click: remove EmberLedger data"] = "Shift + ПКМ: удалить данные EmberLedger",
    ["just now"] = "только что",
    ["%dm ago"] = "%d мин. назад",
    ["%dh %02dm ago"] = "%d ч. %02d мин. назад",
    ["%dd ago"] = "%d дн. назад",
    ["Cooldown tooltip unavailable: %s"] = "Подсказка о восстановлении недоступна: %s",

    ["Currently tracking: %s"] = "Сейчас отслеживается: %s",
    ["All supported cooldown crafts are now shown."] = "Теперь отображаются все поддерживаемые крафты с временем восстановления.",
    ["Quick launcher and window toggle."] = "Быстрый запуск и переключение окна.",
    ["Next CD: Ready on %s"] = "След. восстановление: готово на %s",
    ["Next CD: %s in %s"] = "След. восстановление: %s через %s",

    ["Item"] = "Предмет",
    ["Qty"] = "Кол-во",
    ["Value"] = "Стоимость",
    ["Total"] = "Всего",
    ["Ready: %d | Soon: %d | Mulch: %d"] = "Готово: %d | Скоро: %d | Мульча: %d",

    ["No tracked characters yet. Open professions to scan characters."] = "Нет отслеживаемых персонажей. Откройте профессии, чтобы просканировать их.",
    ["All tracked characters are hidden. Use Restore to show them."] = "Все отслеживаемые персонажи скрыты. Используйте «Восстановить», чтобы показать их.",
    ["No attention rows. Restore hidden or turn off Attention Only."] = "Нет строк, требующих внимания. Восстановите скрытые или отключите «Только требующие внимания».",
    ["No characters need attention."] = "Ни один персонаж не требует внимания.",
    ["No visible character data. Open a profession window to refresh."] = "Нет видимых данных о персонажах. Откройте окно профессии для обновления.",

    ["Sort by %s"] = "Сортировка по: %s",
    ["Click again to reverse the order."] = "Нажмите еще раз, чтобы изменить порядок сортировки.",
    ["EmberLedger options"] = "Настройки EmberLedger",
    ["Restore hidden characters"] = "Восстановить скрытых персонажей",
    ["Right-click a row to hide a character."] = "ПКМ по строке, чтобы скрыть персонажа.",
    ["Collapse or expand character cooldowns"] = "Свернуть или развернуть восстановления персонажа",
    ["Resize tracker height"] = "Изменить высоту трекера",
    ["Drag to change how many character rows are visible."] = "Перетаскивайте, чтобы изменить количество видимых строк персонажей.",
    ["Width remains automatic based on visible columns."] = "Ширина по-прежнему подстраивается автоматически под видимые колонки.",
    ["Double-click to reset automatic height."] = "Двойной клик, чтобы сбросить высоту по умолчанию.",

    ["General"] = "Общие",
    ["Launcher"] = "Запуск",
    ["Session"] = "Сессия",
    ["Main Window"] = "Главное окно",
    ["Action Bar"] = "Панель команд",
    ["Performance"] = "Производительность",
    ["Maintenance"] = "Обслуживание",
    ["Maintenance / Resets"] = "Обслуживание / Сброс данных",
    ["Information"] = "Информация",
    ["Version: %s"] = "Версия: %s",
    ["Version %s"] = "Версия %s",
    ["Profession tracking, Imbued Mulch cooldowns, and session analytics for your alt army."] = "Отслеживание профессий, времени восстановления Настоянной мульчи и аналитика сессий для вашей армии альтов.",
    ["Open EmberLedger Settings"] = "Открыть настройки EmberLedger",

    ["Reset"] = "Сброс",
    ["Clear History"] = "Очистить историю",
    ["Reset Lifetime"] = "Сбросить общую статистику",
    ["Unhide All"] = "Показать всех",
    ["Remove Data"] = "Удалить данные",
    ["Reset all EmberLedger window positions? Scale and visibility settings will be kept."] = "Сбросить расположение всех окон EmberLedger? Настройки масштаба и видимости будут сохранены.",
    ["Reset the current session totals and tracked item list?"] = "Сбросить итоги текущей сессии и список отслеживаемых предметов?",
    ["Clear all saved account-wide session history? This cannot be undone."] = "Очистить всю сохраненную историю сессий для всей учетной записи? Это действие нельзя отменить.",
    ["Reset EmberLedger lifetime session stats? This cannot be undone. Session history will not be deleted."] = "Сбросить общую статистику сессий EmberLedger за все время? Это действие нельзя отменить. История сессий удалена не будет.",
    ["Unhide all hidden characters and return them to the main window table?"] = "Показать всех скрытых персонажей и вернуть их в таблицу главного окна?",
    ["Remove all EmberLedger data for currently hidden characters? This only affects EmberLedger saved data and cannot be undone."] = "Удалить все данные EmberLedger для скрытых в данный момент персонажей? Это повлияет только на сохраненные данные аддона, действие нельзя отменить.",
    ["Remove EmberLedger data for %s? This only affects EmberLedger saved data and cannot be undone."] = "Удалить данные EmberLedger для %s? Это повлияет только на сохраненные данные аддона, действие нельзя отменить.",
    ["Remove all pinned character markers? Character data will not be deleted."] = "Удалить все метки закрепленных персонажей? Данные самих персонажей удалены не будут.",
    ["Confirmation dialog unavailable. No data was removed."] = "Окно подтверждения недоступно. Данные не были удалены.",

    ["Commands:"] = "Команды:",
    ["/el or /ember - Toggle EmberLedger launcher/main view."] = "/el или /ember - показать/скрыть кнопку запуска или главное окно EmberLedger.",
    ["/el main - Toggle the main tracking window."] = "/el main - показать/скрыть главное окно отслеживания.",
    ["/el settings - Open Options."] = "/el settings - открыть настройки.",
    ["/el session - Toggle the standalone Session window."] = "/el session - показать/скрыть отдельное окно сессии.",
    ["/el history - Toggle Session History / Stats."] = "/el history - показать/скрыть историю и статистику сессий.",
    ["/el session start or /el session resume - Resume session tracking."] = "/el session start или /el session resume - возобновить отслеживание сессии.",
    ["/el session pause - Pause session tracking."] = "/el session pause - приостановить отслеживание сессии.",
    ["/el refresh - Refresh tracked profession data."] = "/el refresh - обновить данные отслеживаемых профессий.",
    ["/el scale - Show the current main window scale."] = "/el scale - показать текущий масштаб главного окна.",
    ["/el scale 0.85 - Set main window scale from 0.60 to 1.40."] = "/el scale 0.85 - установить масштаб главного окна (от 0.60 до 1.40).",
    ["/el threshold 900 - Set concentration alert threshold."] = "/el threshold 900 - установить порог оповещения о концентрации.",
    ["/el lock or /el unlock - Lock or unlock EmberLedger windows."] = "/el lock или /el unlock - заблокировать или разблокировать окна EmberLedger.",
    ["/el reset layout - Reset window positions."] = "/el reset layout - сбросить расположение окон.",
    ["/el reset session - Reset current session totals."] = "/el reset session - сбросить итоги текущей сессии.",
    ["/el restore or /el restore hidden - Restore hidden characters."] = "/el restore или /el restore hidden - восстановить скрытых персонажей.",
    ["/el reset pinned - Remove all pinned markers."] = "/el reset pinned - удалить все метки закрепленных персонажей.",
    ["Window scale set to %.2f."] = "Масштаб окна изменен на %.2f.",
    ["Use /el scale 0.6 through /el scale 1.4"] = "Используйте значения от /el scale 0.6 до /el scale 1.4",
    ["Current window scale: %.2f. Use /el scale 0.85, /el scale 1, etc."] = "Текущий масштаб окна: %.2f. Используйте /el scale 0.85, /el scale 1 и т. д.",
    ["Windows locked. Hold Shift and drag to move them."] = "Окна заблокированы. Удерживайте Shift и перетаскивайте их мышью.",
    ["Windows unlocked."] = "Окна разблокированы.",
    ["Refreshed."] = "Обновлено.",
    ["Profession identity refreshed."] = "Данные о профессиях обновлены.",
    ["Profession identity could not be refreshed yet."] = "Пока не удалось обновить данные о профессиях.",
    ["Session tracking resumed."] = "Отслеживание сессии возобновлено.",
    ["Session tracking paused."] = "Отслеживание сессии приостановлено.",
    ["Concentration alert threshold set to %d."] = "Порог оповещения о концентрации установлен на %d.",
    ["Welcome to EmberLedger"] = "Добро пожаловать в EmberLedger",
    ["EmberLedger learns your profession characters as you visit them.\n\nGetting Started:\n1. Log into each profession character you want to track.\n2. Open the Trade Skill window (press K, then choose a profession) once.\n3. Repeat this for each profession alt.\n\nConcentration, Artisan Moxie, and profession cooldowns are only available after opening the profession window. Your dashboard updates automatically as more characters are scanned.\n\nTip: /el help lists all commands and row interactions."] = "EmberLedger запоминает ваших персонажей с профессиями по мере их посещения.\n\nС чего начать:\n1. Зайдите за каждого персонажа, чьи профессии вы хотите отслеживать.\n2. Один раз откройте окно профессии (нажмите клавишу K, затем выберите профессию).\n3. Повторите это для каждого альта с профессиями.\n\nКонцентрация, сноровка и время восстановления рецептов станут доступны только после открытия окна соответствующей профессии. Панель аддона будет обновляться автоматически по мере сканирования персонажей.\n\nСовет: команда /el help выводит список всех команд и способов взаимодействия со строками.",
    ["Open Options"] = "Открыть настройки",
    ["Got It"] = "Понятно",
    },
}

local overrides = localeOverrides[EL.locale]
if overrides then
    for key, value in pairs(overrides) do
        if value ~= nil then
            L[key] = value
        end
    end
end

function EL:GetLocalizationTable()
    return self.L or L
end
